---
name: Gitleaks
"on":
    push:
    workflow_dispatch:
    schedule:
        - cron: "0 4 * * *" # run once a day at 4 AM
    pull_request:

jobs:
    gitleaks:
        timeout-minutes: 60
        name: gitleaks
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6.0.0
              with:
                  fetch-depth: 0

            - uses: gitleaks/gitleaks-action@v2.3.9
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
